import type { PlatformConfig, PlatformId } from './types';

export const platformConfigs: Record<PlatformId, PlatformConfig> = {
  facebook: {
    id: 'facebook',
    name: 'Facebook',
    icon: '📘',
    color: '#1877F2',
    supportedContentTypes: ['text', 'image', 'video', 'link'],
    maxContentLength: 63206,
    requiresMediaUpload: true,
    supportsScheduling: true,
    supportsRecurring: false,
    supportsAnalytics: true,
  },
  instagram: {
    id: 'instagram',
    name: 'Instagram',
    icon: '📷',
    color: '#E4405F',
    supportedContentTypes: ['image', 'video'],
    maxContentLength: 2200,
    requiresMediaUpload: true,
    supportsScheduling: true,
    supportsRecurring: false,
    supportsAnalytics: true,
  },
  twitter: {
    id: 'twitter',
    name: 'Twitter / X',
    icon: '𝕏',
    color: '#000000',
    supportedContentTypes: ['text', 'image', 'video', 'link'],
    maxContentLength: 280,
    requiresMediaUpload: true,
    supportsScheduling: true,
    supportsRecurring: false,
    supportsAnalytics: true,
  },
  tiktok: {
    id: 'tiktok',
    name: 'TikTok',
    icon: '🎵',
    color: '#000000',
    supportedContentTypes: ['video'],
    maxContentLength: 5000,
    requiresMediaUpload: true,
    supportsScheduling: true,
    supportsRecurring: false,
    supportsAnalytics: true,
  },
  youtube: {
    id: 'youtube',
    name: 'YouTube',
    icon: '📹',
    color: '#FF0000',
    supportedContentTypes: ['video', 'text'],
    maxContentLength: 5000,
    requiresMediaUpload: true,
    supportsScheduling: true,
    supportsRecurring: false,
    supportsAnalytics: true,
  },
  telegram: {
    id: 'telegram',
    name: 'Telegram',
    icon: '✈️',
    color: '#0088CC',
    supportedContentTypes: ['text', 'image', 'video'],
    maxContentLength: 4096,
    requiresMediaUpload: true,
    supportsScheduling: false,
    supportsRecurring: false,
    supportsAnalytics: false,
  },
  linkedin: {
    id: 'linkedin',
    name: 'LinkedIn',
    icon: '💼',
    color: '#0A66C2',
    supportedContentTypes: ['text', 'image', 'video', 'link'],
    maxContentLength: 3000,
    requiresMediaUpload: true,
    supportsScheduling: true,
    supportsRecurring: false,
    supportsAnalytics: true,
  },
};

export function getPlatformConfig(platformId: PlatformId): PlatformConfig {
  return platformConfigs[platformId];
}
