export const MANUAL_PUBLISH_SUGGESTIONS: string[] = [
  'Save drafts automatically every 5 seconds with conflict-safe restoration.',
  'Show best-time recommendation per account and platform.',
  'Support queue slots with weekday/time windows.',
  'Add approval workflow: draft, pending, approved, rejected.',
  'Allow multi-level approvals for agency teams.',
  'Add content lock after approval to avoid accidental edits.',
  'Enable campaign tagging with analytics rollups.',
  'Add first-comment support where platform allows it.',
  'Auto-generate UTM parameters from campaign presets.',
  'Validate forbidden words and policy terms before publish.',
  'Add duplicate-content guard across accounts and platforms.',
  'Add language detection with locale-specific warnings.',
  'Provide hashtag quality scoring and overuse warnings.',
  'Suggest emoji and text variants optimized per platform.',
  'Provide media safety checks: file size, duration, aspect ratio.',
  'Add smart crop overlays for reels/shorts/feed previews.',
  'Require alt text for image publishing policies.',
  'Detect low-contrast text overlays on images.',
  'Add built-in image resize and video trim presets.',
  'Support media library with folders, tags, and reuse tracking.',
  'Add account groups for brand, market, and campaign selection.',
  'Allow template packs with pre-selected account groups.',
  'Allow platform-specific template overrides per campaign.',
  'Add bulk scheduling import from CSV.',
  'Provide timeline collision detection and reschedule suggestions.',
  'Add pause-all emergency switch for scheduled content.',
  'Support timezone-per-brand scheduling defaults.',
  'Enable one-click repost and evergreen recycling windows.',
  'Add post performance prediction before publish.',
  'Add post scorecard based on platform-specific best practices.',
  'Track publication latency and retry reliability metrics.',
  'Add webhook notifications for scheduled/published/failed events.',
  'Allow custom Slack/Email alerts per failure severity.',
  'Expose publish API with idempotency keys for integrations.',
  'Add role-based permissions for compose, approve, publish, analytics.',
  'Provide full audit log for every publish change.',
  'Enable client-facing read-only and approve-only portal modes.',
  'Add unified inbox with comment and DM triage.',
  'Support smart routing for inbox assignments by keyword.',
  'Enable saved replies and AI tone rewrite for support teams.',
  'Provide sentiment tags and urgency-based SLA timers.',
  'Add response templates per platform and language.',
  'Support A/B caption variants for scheduled content.',
  'Track per-template conversion and engagement outcomes.',
  'Generate weekly optimization recommendations automatically.',
  'Add competitor watch feed for messaging inspiration.',
  'Provide compliance mode with required legal disclosures.',
  'Add accessibility checklist before publishing.',
  'Enable archive and clone workflow for high-performing posts.',
  'Support mobile quick approve and quick publish actions.',
];
